development:
  adapter: postgresql
  encoding: unicode
  database: antipattern_dev
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: antipattern_test
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
